### ISSUE TITLE
Have texlive install retry after a few seconds if it doesn't complete the first time

### ISSUE THREAD

**Issue by jchodera** [omnia-md/virtual-machines#14]
`texlive` net-install has been occasionally doing this annoying thing where it craps out partway through.  It should be possible to resume by re-running the installer with `sudo ./install-tl -profile installation.profile`.

**Comment by kyleabeauchamp** [comment]
I think this is done now.  Still doesn't work 100% of the time, because I think the failures are correlated and sometimes occur repeatedly when one mirror goes down.
