### ISSUE TITLE
Describe jenkins stuff on wiki (possibly private)?

### ISSUE THREAD

**Issue by kyleabeauchamp** [omnia-md/virtual-machines#20]
It might be good to do a brain dump of info on the jenkins setup, either here or on the choderalab wiki

**Comment by jchodera** [comment]
Good idea.  Does it make sense to do it in this repo, or a separate `omnia-md/jenkins` repo?

**Comment by kyleabeauchamp** [comment]
Not separate.  We have too many repos to keep track of.

**Comment by jchodera** [comment]
OK, will add. Just thought it might be nonobvious that we should look for
the wiki in a repo called 'virtual-machines' if we're looking for info on
'jenkins'.

**Comment by kyleabeauchamp** [comment]
We can expand the scope / title of this repo to "continuous integration" if necessary.  Still better than another repo IMHO.

**Comment by jchodera** [comment]
How's this?
https://github.com/omnia-md/virtual-machines/wiki

**Comment by rmcgibbo** [comment]
Looks good.

**Comment by rmcgibbo** [comment]
Maybe also describe how the linux VMs actually makes its way from the provisioning script to a box on the macmini?

**Comment by jchodera** [comment]
Thanks! Happy to expand as requested.

**Comment by kyleabeauchamp** [comment]
Looks good to me too

**Comment by jchodera** [comment]
Feel free to close for now, though it might be a good idea to link to it
from README.md so we remember it exists.

**Comment by rmcgibbo** [comment]
yeah, link on readme would be good. I never check the wiki for github
projects unless I see a link to it.

**Comment by kyleabeauchamp** [comment]
I updated the readme with a link

**Comment by jchodera** [comment]
Thanks!
